joint_limits:
  arm_1_joint:
#    has_position_limits: true
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.4
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0
  arm_2_joint:
#    has_position_limits: true
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.4
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0
  arm_3_joint:
#    has_position_limits: true
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.4
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0
  arm_4_joint:
#    has_position_limits: true
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.4
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0
  arm_5_joint:
#    has_position_limits: true
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.4
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0
  arm_6_joint:
#    has_position_limits: true
#    min_position: -2.0943951
#    max_position: 2.0943951
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0
