joint_names: ["arm_1_joint","arm_2_joint","arm_3_joint","arm_4_joint","arm_5_joint","arm_6_joint"]
action_name: /arm/joint_trajectory_controller/follow_joint_trajectory
service_ns: /arm/driver
default_vel: 0.3

# back side positions
home: [[0,0,0,0,0,0]]
folded: [[0.0,-0.7462504282752155, -0.5695882013883494, -1.0179807395182126, 0.03600614246864302, 0.49300315381083826]]
waveleft: [[0.0,0.321033880484058, 0.49950722659008573, -0.4061025056033145, -0.2370251233291425, 5.300248440143207e-06]]
waveright: [[0.0,0.4741062629069983, -0.7912476227793528, 0.0041526706870680385, -2.4662076334003302e-05, 2.4489075676648042e-05]]

# trajectories
wave: [waveleft,waveright,home]
