#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

group1:
  group_name: sdh
  component_name: sdh
  buttons: [[stop,trigger,stop],
    [init,trigger,init],
    [home,move,home],
    [cyl. closed,move,cylclosed],
    [cyl. open,move,cylopen],
    [spher. closed,move,spherclosed],
    [spher. open,move,spheropen],
    [point,move,point],
    [fist,move,fist]]

