joint_names: ["arm_1_joint","arm_2_joint","arm_3_joint","arm_4_joint","arm_5_joint","arm_6_joint","arm_7_joint"]

# back side positions
home: [[0,0,0,0,0,0,0]]
folded: [[2.370025500646621, -0.5311859920693394, -0.020293423009077216, -1.642119512558688, 3.011235366157642, 0.7137523530704222, 1.8089394432167776]]
wave_left: [[1.2813282522075768, -0.5604587174568723, 1.697568467520166, -0.2933011486025743, -0.7806437562659001, 0.7139158814922055, 1.8089177286531033]]
wave_right: [[1.2812204894103862, -0.5631183045561761, 0.05981557913023572, 1.3939983144133645, -0.38443088685768156, 0.5648065661512476, 1.6379496641605815]]

# trajectories
wave_left-wave_right-home: [wave_left,wave_right,home]
